services:
  - type: web
    name: oricform2
    env: docker
    plan: free
    repo: https://github.com/RohanSiddiqui/Oricform2
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/Oricform2.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: "Production"
